//Accommodation exports here
export const FETCH_ACCOMMODATION = 'FETCH_ACCOMMODATION';
export const FETCH_ACCOMMODATION_BY_ID_SUCCESS =
'FETCH_ACCOMMODATION_BY_ID_SUCCESS';
export const FETCH_ACCOMMODATION_BY_ID_INIT =
'FETCH_ACCOMMODATION_BY_ID_INIT';
export const FETCH_ACCOMMODATION_SUCCESS = 'FETCH_ACCOMMODATION_SUCCESS';
export const FETCH_ACCOMMODATION_INIT = 'FETCH_ACCOMMODATION_INIT';
export const FETCH_ACCOMMODATION_FAIL = 'FETCH_ACCOMMODATION_FAIL';
//Feedback exports here

export const FETCH_USERFEEDBACK_INIT = 'FETCH_USERFEEDBACK_INIT';
export const FETCH_USERFEEDBACK_SUCCESS = 'FETCH_USERFEEDBACK_SUCCESS';
export const FETCH_USERFEEDBACK_FAIL = 'FETCH_USERFEEDBACK_FAIL';
export const FETCH_FEEDBACK_FAIL = 'FETCH_FEEDBACK_FAIL';
export const FETCH_FEEDBACK_SUCCESS = 'FETCH_FEEDBACK_SUCCESS';
export const FETCH_FEEDBACK_INIT = 'FETCH_FEEDBACK_INIT';


//export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
//export const LOGIN_FAIL = 'LOGIN_FAIL';
//export const LOGOUT = 'LOGOUT';
